"""
Audit logger.

Persists every query to a file-based SQLite database (WAL mode for safe
concurrent writes from multiple uvicorn workers) and streams a JSON record to
stdout so Railway / any log aggregator captures it permanently.

PostgreSQL backend (optional)
------------------------------
When DATABASE_URL is set, each audit record is ALSO written to the PostgreSQL
audit_log table (see db/postgres.py).  This provides a durable, shared audit
trail that survives container restarts and is visible to all workers.

In ``recent()`` PostgreSQL is preferred when available; SQLite is used as
fallback so the audit endpoint always returns data even without PostgreSQL.

SQLite file path: AUDIT_DB_PATH env var (default: /tmp/audit.db).
In-process the file survives restarts within a Railway deployment; for true
persistence across deploys attach a Railway volume and point AUDIT_DB_PATH at it.

Schema (SQLite fallback)
------
id             Auto-incremented primary key
ts             ISO-8601 UTC timestamp
question       Original natural-language question
sql_generated  Final SQL sent to Snowflake (null on early failures)
success        1 = result returned, 0 = error
row_count      Rows returned (null on failure)
latency_ms     Wall-clock time for the full pipeline (ms)
cache_hit      1 = result served from cache, 0 = Snowflake was queried
pii_detected   Comma-separated PII type names found in results (empty string if none)
error_message  Error detail when success = 0
"""

import json
import logging
import os
import sqlite3
import threading
from datetime import datetime, timezone

logger = logging.getLogger(__name__)

_DB_PATH = os.environ.get("AUDIT_DB_PATH", "/tmp/audit.db")
_lock = threading.Lock()
_conn = sqlite3.connect(_DB_PATH, check_same_thread=False)


def _init() -> None:
    _conn.execute("PRAGMA journal_mode=WAL")
    _conn.execute("PRAGMA synchronous=NORMAL")
    with _conn:
        _conn.execute("""
            CREATE TABLE IF NOT EXISTS audit_log (
                id            INTEGER PRIMARY KEY AUTOINCREMENT,
                ts            TEXT    NOT NULL,
                question      TEXT    NOT NULL,
                sql_generated TEXT,
                success       INTEGER NOT NULL,
                row_count     INTEGER,
                latency_ms    INTEGER,
                cache_hit     INTEGER NOT NULL DEFAULT 0,
                pii_detected  TEXT    NOT NULL DEFAULT '',
                error_message TEXT
            )
        """)


_init()


def _record_postgres(
    ts: str,
    question: str,
    sql: str | None,
    success: bool,
    row_count: int | None,
    latency_ms: int | None,
    cache_hit: bool,
    pii_str: str,
    error: str | None,
) -> None:
    """Write one record to the PostgreSQL audit_log table (best-effort)."""
    try:
        from db import postgres  # noqa: PLC0415
        if not postgres.is_available():
            return
        postgres.query(
            """
            INSERT INTO audit_log
                (ts, question, sql_generated, success, row_count,
                 latency_ms, cache_hit, pii_detected, error_message)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
            """,
            (ts, question, sql, success, row_count,
             latency_ms, cache_hit, pii_str, error),
        )
    except Exception as exc:  # noqa: BLE001
        logger.warning("PostgreSQL audit insert failed: %s", exc)


def record(
    question: str,
    sql: str | None,
    success: bool,
    row_count: int | None = None,
    latency_ms: int | None = None,
    cache_hit: bool = False,
    pii_detected: list[str] | None = None,
    error: str | None = None,
) -> None:
    """
    Insert one audit record into both PostgreSQL (if available) and SQLite,
    and stream it to stdout as structured JSON.

    Parameters
    ----------
    question:      Original natural-language question.
    sql:           SQL generated by the pipeline, or None on early failure.
    success:       True when results were returned.
    row_count:     Number of rows returned (None on failure).
    latency_ms:    Wall-clock time for the full pipeline.
    cache_hit:     True when the result came from the cache.
    pii_detected:  List of PII type names found in the results.
    error:         Error message when success=False.
    """
    ts = datetime.now(timezone.utc).isoformat()
    pii_str = ",".join(pii_detected) if pii_detected else ""

    # 1. PostgreSQL (best-effort, non-blocking on failure)
    _record_postgres(ts, question, sql, success, row_count, latency_ms, cache_hit, pii_str, error)

    # 2. SQLite (always)
    with _lock:
        with _conn:
            _conn.execute(
                """
                INSERT INTO audit_log
                    (ts, question, sql_generated, success, row_count,
                     latency_ms, cache_hit, pii_detected, error_message)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (ts, question, sql, int(success), row_count,
                 latency_ms, int(cache_hit), pii_str, error),
            )

    # 3. Stdout JSON
    logger.info(json.dumps({
        "event": "query",
        "ts": ts,
        "question": question,
        "success": success,
        "row_count": row_count,
        "latency_ms": latency_ms,
        "cache_hit": cache_hit,
        "pii_detected": pii_detected or [],
        "error": error,
    }))


def recent(limit: int = 100) -> list[dict]:
    """
    Return the most recent *limit* audit entries, newest first.

    Queries PostgreSQL when available; falls back to SQLite otherwise.
    """
    # Try PostgreSQL first
    try:
        from db import postgres  # noqa: PLC0415
        if postgres.is_available():
            rows = postgres.query(
                """
                SELECT id, ts::text, question, sql_generated, success,
                       row_count, latency_ms, cache_hit, pii_detected, error_message
                FROM audit_log
                ORDER BY id DESC
                LIMIT %s
                """,
                (limit,),
            )
            if rows is not None:
                for r in rows:
                    r["ts"] = str(r["ts"])
                    r["success"] = bool(r["success"])
                    r["cache_hit"] = bool(r["cache_hit"])
                    r["pii_detected"] = (
                        r["pii_detected"].split(",") if r.get("pii_detected") else []
                    )
                return rows
    except Exception as exc:  # noqa: BLE001
        logger.warning("PostgreSQL audit read failed, falling back to SQLite: %s", exc)

    # Fall back to SQLite
    with _lock:
        cur = _conn.execute(
            """
            SELECT id, ts, question, sql_generated, success,
                   row_count, latency_ms, cache_hit, pii_detected, error_message
            FROM audit_log
            ORDER BY id DESC
            LIMIT ?
            """,
            (limit,),
        )
        cols = [d[0] for d in cur.description]
        rows = [dict(zip(cols, row)) for row in cur.fetchall()]

    for r in rows:
        r["success"] = bool(r["success"])
        r["cache_hit"] = bool(r["cache_hit"])
        r["pii_detected"] = r["pii_detected"].split(",") if r["pii_detected"] else []

    return rows
